name: node_registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ROS_DISTRO: foxy
  ROS_VERSION: ros2
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DETRABOT_SECRET}}
          path: node_registry
          clean: true

      - name: Clone deepx_ros_test
        uses: actions/checkout@v2
        with:
          repository: DeepX-inc/deepx_ros_test
          path: deepx_ros_test
          ref: feature/test_common_utils
          ssh-key: ${{ secrets.DETRABOT_SECRET}}
          clean: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: build and test
        run: |
          export DOCKER_IMAGE=krishneel/ros2-foxy:latest
          export REPO_NAME=${{ github.event.repository.name }}
          export ADD_REPO_NAME=deepx_ros_test
          export HOME=$GITHUB_WORKSPACE

          docker run -v $HOME:$HOME -e ADD_REPO_NAME -e REPO_NAME -e HOME $DOCKER_IMAGE bash -c 'cd $HOME; source ./node_registry/.github/action.sh'
