name: node_registry

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ROS_DISTRO: foxy
  ROS_VERSION: ros2
  DEBIAN_FRONTEND: noninteractive

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      INSTALL_DIR: ./install

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DETRABOT_SECRET}}
          path: ${{ env.INSTALL_DIR }}/node_registry
          clean: true

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: build and test
        run: |
          export DOCKER_IMAGE=ros:foxy
          export REPO_NAME=${{ github.event.repository.name }}
          export HOME=$GITHUB_WORKSPACE
          export ACTION_BUILD_DIR=$(pwd)/$INSTALL_DIR

          docker run -v $HOME:$HOME -e ACTION_BUILD_DIR -e REPO_NAME -e HOME $DOCKER_IMAGE bash -c 'cd $ACTION_BUILD_DIR; source ./node_registry/.github/action.sh'
